-- MySQL Script generated by MySQL Workbench
-- qua 06 mai 2020 12:05:53 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `locadora` ;

-- -----------------------------------------------------
-- Schema locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `locadora` DEFAULT CHARACTER SET utf8 ;
USE `locadora` ;

-- -----------------------------------------------------
-- Table `locadora`.`Locacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `locadora`.`Locacoes` ;

CREATE TABLE IF NOT EXISTS `locadora`.`locacoes` (
  `idlocacao` INT NOT NULL,
  `nomelocatario` VARCHAR(45) NOT NULL,
  `modeloveiculo` VARCHAR(45) NOT NULL,
  `marcaveiculo` VARCHAR(45) NOT NULL,
  `anomodeloveiculo` CHAR(4) NOT NULL,
  `anofabricacaveiculo` CHAR(4) NOT NULL,
  `placaveiculo` CHAR(8) NOT NULL,
  PRIMARY KEY (`idlocacao`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
